#!/bin/bash
# Generated by install-solr-core-delta-import-cron.sh on {today}
if [ $({zkcli} -zkhost {zkhosts} -cmd get /configs/{core}/dataimport-status.txt) -eq 1 ]; then
	if [ $({zkbindir}zkServer.sh status 2>&1 | grep "Mode: leader" -c) -eq 1 ]; then
		if [ $(curl "http://{host}:8983/solr/{core}/dataimport/?command=status&wt=json&indent=true" 2>&1 | grep idle | wc -l) -gt 0 ];  then
			if [ "$1" = "optimize" ]; then			
				curl -u {curlcredentials} "http://{host}:8983/solr/{core}/dataimport/?command=delta-import&optimize=true"
				#curl -u {curlcredentials} "http://{host}:8983/solr/{core}/update?optimize=true&waitFlush=true"
			else
				curl -u {curlcredentials} "http://{host}:8983/solr/{core}/dataimport/?command=delta-import"
			fi
		fi
	fi
fi